import React from "react";
import { BrowserRouter } from "react-router-dom";
export const movies = [
  "Army of Thieves",
  "Army of the Dead",
  "Interstellar",
  "Inception",
  "Tenet",
  "Shawshank Redemption",
  "Green Mile",
  "John Wick",
  "Nobody",
  "Divergent",
  "Maze Runner",
  "Wanted (Hollywood)",
  "Suicide Squad",
  "Overload",
  "Anweshippin Kandethum",
  "Kingsman",
  "Hangover",
  "Lucky Bhaskar",
  "Transformers",
  "Godzilla + Kong: Minus One",
  "Fast and Furious",
  "Rampage",
  "San Andreas",
  "The Day After Tomorrow",
  "Get Out",
  "10 Cloverfield Lane",
  "Source Code",
  "Code 8",
  "Heart of Stone",
  "Tron: Legacy",
  "The Wild Robot",
  "Top Gun: Maverick",
  "Rush Hour",
  "The Terminal",
  "The Matrix",
  "Final Destination",
  "The Martian",
  "Prometheus",
  "Annihilation",
  "John Carter",
  "A Quiet Place",
  "Escape Room",
  "Resident Evil",
  "Planet of the Apes",
  "Jurassic World",
  "Terminator Series",
  "Train to Busan",
  "Shutter Island",
  "I Saw the Devil",
  "The Great Wall",
  "Prince of Persia",
  "300",
  "It",
  "I Am Legend",
  "Pacific Rim",
  "Uncharted",
  "Skyscraper",
  "Into the Wild",
  "The Adam Project",
  "Mortal Kombat",
  "Abraham Lincoln: Vampire Hunter",
  "Ready Player One",
  "Red Notice",
  "Alive",
  "The Platform",
  "Predestination",
  "Alien",
  "Predator",
  "Edge of Tomorrow",
  "Tomorrow War",
  "Prometheus",
  "Mortal Engines",
  "Life",
  "Tomorrowland",
  "65",
  "Gemini Man",
  "Everything Everywhere All at Once",
  "World War Z",
  "Wall-E",
  "I, Robot",
  "The Prisoner",
  "Hi Nanna",
  "Taqdeer",
  "Warcraft",
  "Battleship",
  "Sector 36",
  "Ek Banda Hi Kafi Hai",
  "Project Power",
  "The Shadow of the Moon",
  "Olympus Has Fallen",
  "London Has Fallen",
  "Angel Has Fallen",
  "Back in Action",
  "Beast (Hollywood)",
  "King Arthur",
  "Guardians(Russian version)",
  "Monster Hunter",
  "Dhoom Dhaam",
  "Trapped (Bollywood)",
  "The Sorcerer's Apprentice",
  "Midnight Runner",
  "Night Teeth",
  "Layover",
  "Lift",
  "The Man from Toronto",
  "Fatherhood",
  "Night School",
  "The Upside",
  "The Wedding Ringer",
  "The Grey Man",
  "Boyka: Undisputed",
  "Blood Diamond",
  "The Darkest Hour",
  "Rekhachithram",
  "The 5th Wave",
  "Bloodshot",
  "6 Underground",
  "Hitman's Wife's Bodyguard",
  "Free Guy",
  "The Menu",
  "What You Wish For",
  "Fall",
  "Moonfall",
  "Bullet Train Explosion",
  "In the Heart of the Sea",
  "Novocaine",
  "Up in the Air",
  "Coconut",
  "The Good Dinosaur",
  "The Most Dangerous Game",
  "13 Hours: The Secret Soldiers of Benghazi",
  "Extraction",
  "World Invasion: Los Angeles",
  "Tears of the Sun",
  "G.I. Joe (series)",
  "Instant Family",
  "The Day the Earth Stood Still",
  "The Intern",
  "The Silence",
  "Padakkalam",
  "The Accountant 2",
  "Green Book",
  "Elevation",
  "M3GAN",
  "Heads of State",
  "Catch Me If You Can",
];
export const series = [
  "Fear the Walking Dead",
  "Lupin",
  "From",
  "Locke & Key",
  "Alice in Borderland",
  "Railwayman",
  "Reacher",
  "You",
  "Dark",
  "All of Us Are Dead",
  "Loko",
  "Suits",
  "Breaking Bad",
  "Inspector Rishi",
  "Citadel: Honey Bunny",
  "Betaal",
  "Kaala Paani",
  "Sandman",
  "Invincible",
  "Squid Game",
  "Shangri-La Frontier",
  "Vinland Saga",
  "Panchayat",
  "Narcos",
  "Succession",
  "Kota Factory",
  "Black Mirror",
  "The Boys",
  "Stranger Things",
  "The Haunting of Hill House",
  "The Family Man",
  "The Purge",
  "Lucifer",
  "The 8th Show",
  "Them",
  "Bandish Bandits",
  "3 Body Problem",
  "Fallout",
  "the day of jackal",
  "Bloodhounds",
  "jack ryan",
  "better call saul",
  "halo",
  "newtopia",
  "the silent sea",
  "mercy for none",
  "criminal justice",
];

const Ms = ({ children }) => {
  return <div className="layout">{children}</div>;
};

export default Ms;
